apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:IHGCUrPU20HSOzvLRFFutAWuiIap0dy6CqH1ZYxWbBelY1VVJGfrGaJ+WUEqaTrjeoiDqwKrkjqeZzy+7wp5DjQVSgARUEZU7P8aagtgY3Xjj4QwKurzyJk9VztoK1REL19J5kgIgIYSYovpwNXV1ky5mpxKsJ/EMS6EGm7ixR2LtIabeQcs0CZFHbFsyROluLjVH0gM8uBXD5mDaRO1Ks6fPmgCF0HsWd+6qapQpihxOTkj6slXMLbQ6ycrEffGF23RypSosNoK19yhm3GRdc6BpUCparRmeOnSJkUuZarCqCLSXBZAClEcR9c=,iv:Kq6YvL+6IkiLlPWufQbW+8NvrYnIz58ulySyGOJFHDA=,tag:Xd9LrNla0BHByKjDVOf8sQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMVovRnkvUWFjZldjN1hy
            SUIxamV6Qkl3RkRoMUxoSGF1RTJlT3JzN1ZBCjQzblF1MEdDNHhCVDhxT09tT21j
            K0hmV05TTGNHTW9KZVpTMHplWUZOdjgKLS0tIDhGWm50bEFMUlZrakkvVEVmblB5
            eVRFTmJOU1ptYWV4djdNOXNXeUt0MzAKiOag7KvaYMF6VMAuK/VvWVCQzxv/girp
            W1K2iGY827Xupud/xcNb0iXZt4ZtkWmcKvkORigpOCaMW8Zkrv05aw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age160e9yelmgsetr4s25c6ynu5u9qnt8ss4y6r9de747ttzr8s78sdsnphrkg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T22:02:35Z"
    mac: ENC[AES256_GCM,data:LWwp9FLaqIJN6e/ew33eb8XeKoC5cIPIkxKexcDbR8QIZXenBy2w7RYHXvySELEImRW+gq/rXqk1KutOIAuLaPPIhfLW0D9zma2Ou88D+L/DinrZg4jWucrukH05Yy36mqqNGosLmFvWCFq0stJYkv3IQ4RhU+fkVrD8yvNf494=,iv:dHTVSBe8P4vjdIlL2aD4qNSPB0bDGY6IbkxmBmPQrdc=,tag:3RycAIdOtuVyN3dSm682MQ==,type:str]
    version: 3.13.2
